name: ✨ Feature
description: 새로운 기능 개발
title: "Feature: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        **브랜치 생성**: `feature/기능명-설명` (소문자, 대시로 구분)
        
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      placeholder: 키링 음성 메모 기능
    validations:
      required: true
